# Generated by Django 6.0.5 on 2026-05-12 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("incidents", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="incidents.category",
            ),
        ),
    ]
