# Generated by Django 6.0.5 on 2026-05-12 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="avatars/"),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("CITIZEN", "Fuqaro"),
                    ("OPERATOR", "Operator"),
                    ("TECHNICIAN", "Texnik"),
                ],
                default="CITIZEN",
                max_length=20,
            ),
        ),
    ]
