# Generated by Django 6.0.5 on 2026-05-12 04:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incidents", "0002_alter_systemlog_incident"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="incident",
            name="priority",
            field=models.CharField(
                choices=[("LOW", "Past"), ("MEDIUM", "O'rta"), ("HIGH", "Yuqori")],
                default="MEDIUM",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="incident",
            name="status",
            field=models.CharField(
                choices=[
                    ("NEW", "Yangi"),
                    ("IN_PROGRESS", "Jarayonda"),
                    ("RESOLVED", "Bajarildi"),
                    ("CLOSED", "Yopildi"),
                    ("REJECTED", "Rad etildi"),
                ],
                default="NEW",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
