# Generated by Django 6.0.5 on 2026-05-12 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incidents", "0003_alter_incident_priority_alter_incident_status_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="IncidentImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="incidents/")),
                (
                    "incident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="incidents.incident",
                    ),
                ),
            ],
        ),
    ]
