# Generated by Django 6.0.5 on 2026-05-12 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incidents", "0005_incident_result_comment_incident_result_photo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="incident",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feedbacks",
                to="incidents.incident",
            ),
        ),
    ]
